/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Fri Jan 16 01:22:28 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


